In [53]:
import pandas as pd
import numpy as np
df = pd.read_csv('NFL_Players.csv')
df

,#,Age,City,College,Conference,Division,Exp.,Ht.,Name,Pos.,Team,Team Logo,Team Roster,Wt.
0,NaN,NaN,"Atlanta, GA",Minnesota,NFC,NFC-South,NaN,NaN,"Lynn, Jack",LB,Falcons,https://cpt.azureedge.net/NFLTeamImages/falcon...,http://www.atlantafalcons.com/team/player-rost...,0
1,NaN,NaN,"East Rutherford, NJ",Akron,NFC,NFC-East,R,6-3,"Lane, Jerome",WR,Giants,https://cpt.azureedge.net/NFLTeamImages/giants...,http://www.giants.com/team/roster.html,220
2,NaN,NaN,"East Rutherford, NJ",Iowa State,NFC,NFC-East,R,5-10,"Tribune, Nigel",CB,Giants,https://cpt.azureedge.net/NFLTeamImages/giants...,http://www.giants.com/team/roster.html,179
3,1,NaN,"Atlanta, GA",Georgia,NFC,NFC-South,R,6-0,"Davis, Reggie",WR,Falcons,https://cpt.azureedge.net/NFLTeamImages/falcon...,http://www.atlantafalcons.com/team/player-rost...,170
4,11,NaN,"Denver, CO",Louisiana Tech,AFC,AFC-West,R,5-11,"Henderson, Carlos",WR,Broncos,https://cpt.azureedge.net/NFLTeamImages/bronco...,http://www.denverbroncos.com/team/roster.html,199
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2863,92,39.0,"Pittsburg, PA",Kent State,AFC,AFC-North,15,6-0,"Harrison, James",LB,Steelers,https://cpt.azureedge.net/NFLTeamImages/steele...,http://www.steelers.com/team/roster.html,242
2864,9,40.0,"Houston, TX",Texas A&M,AFC,AFC-South,17,6-2,"Lechler, Shane",P,Texans,https://cpt.azureedge.net/NFLTeamImages/texans...,http://www.houstontexans.com/team/roster.html,230
2865,3,42.0,"Atlanta, GA",Baylor,NFC,NFC-South,16,5-9,"Bryant, Matt",K,Falcons,https://cpt.azureedge.net/NFLTeamImages/falcon...,http://www.atlantafalcons.com/team/player-rost...,203
2866,4,42.0,"Glendale, AZ",Texas,NFC,NFC-West,18,5-11,"Dawson, Phil",K,Cardinals,https://cpt.azureedge.net/NFLTeamImages/cardin...,http://www.azcardinals.com/roster/player-roste...,200
2867,4,44.0,"Indianapolis, IN",South Dakota State,AFC,AFC-South,22,6-0,"Vinatieri, Adam",K,Colts,https://cpt.azureedge.net/NFLTeamImages/colts.png,http://www.colts.com/team/roster.html,206

In [54]:
df.info() 
# object means string

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2868 entries, 0 to 2867
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   #            2858 non-null   object
 1   Age          2820 non-null   float64
 2   City         2868 non-null   object
 3   College      2865 non-null   object
 4   Conference   2868 non-null   object
 5   Division     2868 non-null   object
 6   Exp.         2864 non-null   object
 7   Ht.          2867 non-null   object
 8   Name         2868 non-null   object
 9   Pos.         2868 non-null   object
 10  Team         2868 non-null   object
 11  Team Logo    2868 non-null   object
 12  Team Roster  2868 non-null   object
 13  Wt.          2868 non-null   int64
dtypes: float64(1), int64(1), object(12)
memory usage: 313.8+ KB

In [55]:
# string space removal
s = ' hello world  '  
s.strip()  # remove leading / trailing space

'hello world'

In [56]:
# col name can have space, extra char
df.columns

Index(['#', 'Age', 'City', 'College', 'Conference', 'Division', 'Exp.', 'Ht.',
       'Name', 'Pos.', 'Team', 'Team Logo', 'Team Roster', 'Wt.'],
      dtype='object')

In [57]:
# remove space in column header
df.columns = df.columns.str.strip()
df

,#,Age,City,College,Conference,Division,Exp.,Ht.,Name,Pos.,Team,Team Logo,Team Roster,Wt.
0,NaN,NaN,"Atlanta, GA",Minnesota,NFC,NFC-South,NaN,NaN,"Lynn, Jack",LB,Falcons,https://cpt.azureedge.net/NFLTeamImages/falcon...,http://www.atlantafalcons.com/team/player-rost...,0
1,NaN,NaN,"East Rutherford, NJ",Akron,NFC,NFC-East,R,6-3,"Lane, Jerome",WR,Giants,https://cpt.azureedge.net/NFLTeamImages/giants...,http://www.giants.com/team/roster.html,220
2,NaN,NaN,"East Rutherford, NJ",Iowa State,NFC,NFC-East,R,5-10,"Tribune, Nigel",CB,Giants,https://cpt.azureedge.net/NFLTeamImages/giants...,http://www.giants.com/team/roster.html,179
3,1,NaN,"Atlanta, GA",Georgia,NFC,NFC-South,R,6-0,"Davis, Reggie",WR,Falcons,https://cpt.azureedge.net/NFLTeamImages/falcon...,http://www.atlantafalcons.com/team/player-rost...,170
4,11,NaN,"Denver, CO",Louisiana Tech,AFC,AFC-West,R,5-11,"Henderson, Carlos",WR,Broncos,https://cpt.azureedge.net/NFLTeamImages/bronco...,http://www.denverbroncos.com/team/roster.html,199
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2863,92,39.0,"Pittsburg, PA",Kent State,AFC,AFC-North,15,6-0,"Harrison, James",LB,Steelers,https://cpt.azureedge.net/NFLTeamImages/steele...,http://www.steelers.com/team/roster.html,242
2864,9,40.0,"Houston, TX",Texas A&M,AFC,AFC-South,17,6-2,"Lechler, Shane",P,Texans,https://cpt.azureedge.net/NFLTeamImages/texans...,http://www.houstontexans.com/team/roster.html,230
2865,3,42.0,"Atlanta, GA",Baylor,NFC,NFC-South,16,5-9,"Bryant, Matt",K,Falcons,https://cpt.azureedge.net/NFLTeamImages/falcon...,http://www.atlantafalcons.com/team/player-rost...,203
2866,4,42.0,"Glendale, AZ",Texas,NFC,NFC-West,18,5-11,"Dawson, Phil",K,Cardinals,https://cpt.azureedge.net/NFLTeamImages/cardin...,http://www.azcardinals.com/roster/player-roste...,200
2867,4,44.0,"Indianapolis, IN",South Dakota State,AFC,AFC-South,22,6-0,"Vinatieri, Adam",K,Colts,https://cpt.azureedge.net/NFLTeamImages/colts.png,http://www.colts.com/team/roster.html,206

In [58]:
df['Wt.']

0         0
1       220
2       179
3       170
4       199
       ...
2863    242
2864    230
2865    203
2866    200
2867    206
Name: Wt., Length: 2868, dtype: int64

In [59]:
# split fields
'12/12/2020'.split('/')

['12', '12', '2020']

In [60]:
'hello_world'.split('_')[1]

'world'

In [61]:
df

,#,Age,City,College,Conference,Division,Exp.,Ht.,Name,Pos.,Team,Team Logo,Team Roster,Wt.
0,NaN,NaN,"Atlanta, GA",Minnesota,NFC,NFC-South,NaN,NaN,"Lynn, Jack",LB,Falcons,https://cpt.azureedge.net/NFLTeamImages/falcon...,http://www.atlantafalcons.com/team/player-rost...,0
1,NaN,NaN,"East Rutherford, NJ",Akron,NFC,NFC-East,R,6-3,"Lane, Jerome",WR,Giants,https://cpt.azureedge.net/NFLTeamImages/giants...,http://www.giants.com/team/roster.html,220
2,NaN,NaN,"East Rutherford, NJ",Iowa State,NFC,NFC-East,R,5-10,"Tribune, Nigel",CB,Giants,https://cpt.azureedge.net/NFLTeamImages/giants...,http://www.giants.com/team/roster.html,179
3,1,NaN,"Atlanta, GA",Georgia,NFC,NFC-South,R,6-0,"Davis, Reggie",WR,Falcons,https://cpt.azureedge.net/NFLTeamImages/falcon...,http://www.atlantafalcons.com/team/player-rost...,170
4,11,NaN,"Denver, CO",Louisiana Tech,AFC,AFC-West,R,5-11,"Henderson, Carlos",WR,Broncos,https://cpt.azureedge.net/NFLTeamImages/bronco...,http://www.denverbroncos.com/team/roster.html,199
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2863,92,39.0,"Pittsburg, PA",Kent State,AFC,AFC-North,15,6-0,"Harrison, James",LB,Steelers,https://cpt.azureedge.net/NFLTeamImages/steele...,http://www.steelers.com/team/roster.html,242
2864,9,40.0,"Houston, TX",Texas A&M,AFC,AFC-South,17,6-2,"Lechler, Shane",P,Texans,https://cpt.azureedge.net/NFLTeamImages/texans...,http://www.houstontexans.com/team/roster.html,230
2865,3,42.0,"Atlanta, GA",Baylor,NFC,NFC-South,16,5-9,"Bryant, Matt",K,Falcons,https://cpt.azureedge.net/NFLTeamImages/falcon...,http://www.atlantafalcons.com/team/player-rost...,203
2866,4,42.0,"Glendale, AZ",Texas,NFC,NFC-West,18,5-11,"Dawson, Phil",K,Cardinals,https://cpt.azureedge.net/NFLTeamImages/cardin...,http://www.azcardinals.com/roster/player-roste...,200
2867,4,44.0,"Indianapolis, IN",South Dakota State,AFC,AFC-South,22,6-0,"Vinatieri, Adam",K,Colts,https://cpt.azureedge.net/NFLTeamImages/colts.png,http://www.colts.com/team/roster.html,206

In [62]:
# get fields
# df['Ht.'].str.split('-')[1]
df['Ht.'].str.split('-').str[0]  # get foot only

0       NaN
1         6
2         5
3         6
4         5
       ...
2863      6
2864      6
2865      5
2866      5
2867      6
Name: Ht., Length: 2868, dtype: object

In [64]:
df

,#,Age,City,College,Conference,Division,Exp.,Ht.,Name,Pos.,Team,Team Logo,Team Roster,Wt.
0,NaN,NaN,"Atlanta, GA",Minnesota,NFC,NFC-South,NaN,NaN,"Lynn, Jack",LB,Falcons,https://cpt.azureedge.net/NFLTeamImages/falcon...,http://www.atlantafalcons.com/team/player-rost...,0
1,NaN,NaN,"East Rutherford, NJ",Akron,NFC,NFC-East,R,6-3,"Lane, Jerome",WR,Giants,https://cpt.azureedge.net/NFLTeamImages/giants...,http://www.giants.com/team/roster.html,220
2,NaN,NaN,"East Rutherford, NJ",Iowa State,NFC,NFC-East,R,5-10,"Tribune, Nigel",CB,Giants,https://cpt.azureedge.net/NFLTeamImages/giants...,http://www.giants.com/team/roster.html,179
3,1,NaN,"Atlanta, GA",Georgia,NFC,NFC-South,R,6-0,"Davis, Reggie",WR,Falcons,https://cpt.azureedge.net/NFLTeamImages/falcon...,http://www.atlantafalcons.com/team/player-rost...,170
4,11,NaN,"Denver, CO",Louisiana Tech,AFC,AFC-West,R,5-11,"Henderson, Carlos",WR,Broncos,https://cpt.azureedge.net/NFLTeamImages/bronco...,http://www.denverbroncos.com/team/roster.html,199
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2863,92,39.0,"Pittsburg, PA",Kent State,AFC,AFC-North,15,6-0,"Harrison, James",LB,Steelers,https://cpt.azureedge.net/NFLTeamImages/steele...,http://www.steelers.com/team/roster.html,242
2864,9,40.0,"Houston, TX",Texas A&M,AFC,AFC-South,17,6-2,"Lechler, Shane",P,Texans,https://cpt.azureedge.net/NFLTeamImages/texans...,http://www.houstontexans.com/team/roster.html,230
2865,3,42.0,"Atlanta, GA",Baylor,NFC,NFC-South,16,5-9,"Bryant, Matt",K,Falcons,https://cpt.azureedge.net/NFLTeamImages/falcon...,http://www.atlantafalcons.com/team/player-rost...,203
2866,4,42.0,"Glendale, AZ",Texas,NFC,NFC-West,18,5-11,"Dawson, Phil",K,Cardinals,https://cpt.azureedge.net/NFLTeamImages/cardin...,http://www.azcardinals.com/roster/player-roste...,200
2867,4,44.0,"Indianapolis, IN",South Dakota State,AFC,AFC-South,22,6-0,"Vinatieri, Adam",K,Colts,https://cpt.azureedge.net/NFLTeamImages/colts.png,http://www.colts.com/team/roster.html,206

In [81]:
# df['Ht'] = df[df['Ht.']].str.replace("'",'-')
df.dropna()
df['Ht.'] = df['Ht.'].apply(lambda x: str(x).replace("'", "-"))
df['Ht.'] = df['Ht.'].apply(lambda x: str(x).replace('"', "-"))

df['feet'] = df['Ht.'].str.split("-").str[0].astype(float)
df['inch'] = df['Ht.'].str.split("-").str[1].astype(float)

In [82]:
df

,#,Age,City,College,Conference,Division,Exp.,Ht.,Name,Pos.,Team,Team Logo,Team Roster,Wt.,Ht,feet,inch
0,NaN,NaN,"Atlanta, GA",Minnesota,NFC,NFC-South,NaN,nan,"Lynn, Jack",LB,Falcons,https://cpt.azureedge.net/NFLTeamImages/falcon...,http://www.atlantafalcons.com/team/player-rost...,0,NaN,NaN,NaN
1,NaN,NaN,"East Rutherford, NJ",Akron,NFC,NFC-East,R,6-3,"Lane, Jerome",WR,Giants,https://cpt.azureedge.net/NFLTeamImages/giants...,http://www.giants.com/team/roster.html,220,6-3,6.0,3.0
2,NaN,NaN,"East Rutherford, NJ",Iowa State,NFC,NFC-East,R,5-10,"Tribune, Nigel",CB,Giants,https://cpt.azureedge.net/NFLTeamImages/giants...,http://www.giants.com/team/roster.html,179,5-10,5.0,10.0
3,1,NaN,"Atlanta, GA",Georgia,NFC,NFC-South,R,6-0,"Davis, Reggie",WR,Falcons,https://cpt.azureedge.net/NFLTeamImages/falcon...,http://www.atlantafalcons.com/team/player-rost...,170,6-0,6.0,0.0
4,11,NaN,"Denver, CO",Louisiana Tech,AFC,AFC-West,R,5-11,"Henderson, Carlos",WR,Broncos,https://cpt.azureedge.net/NFLTeamImages/bronco...,http://www.denverbroncos.com/team/roster.html,199,5-11,5.0,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2863,92,39.0,"Pittsburg, PA",Kent State,AFC,AFC-North,15,6-0,"Harrison, James",LB,Steelers,https://cpt.azureedge.net/NFLTeamImages/steele...,http://www.steelers.com/team/roster.html,242,6-0,6.0,0.0
2864,9,40.0,"Houston, TX",Texas A&M,AFC,AFC-South,17,6-2,"Lechler, Shane",P,Texans,https://cpt.azureedge.net/NFLTeamImages/texans...,http://www.houstontexans.com/team/roster.html,230,6-2,6.0,2.0
2865,3,42.0,"Atlanta, GA",Baylor,NFC,NFC-South,16,5-9,"Bryant, Matt",K,Falcons,https://cpt.azureedge.net/NFLTeamImages/falcon...,http://www.atlantafalcons.com/team/player-rost...,203,5-9,5.0,9.0
2866,4,42.0,"Glendale, AZ",Texas,NFC,NFC-West,18,5-11,"Dawson, Phil",K,Cardinals,https://cpt.azureedge.net/NFLTeamImages/cardin...,http://www.azcardinals.com/roster/player-roste...,200,5-11,5.0,11.0
2867,4,44.0,"Indianapolis, IN",South Dakota State,AFC,AFC-South,22,6-0,"Vinatieri, Adam",K,Colts,https://cpt.azureedge.net/NFLTeamImages/colts.png,http://www.colts.com/team/roster.html,206,6-0,6.0,0.0

In [85]:
# replace nan in feet column with 0
df.inch.fillna(0, inplace=True)
df.feet.fillna(0, inplace=True)

In [86]:
df

,#,Age,City,College,Conference,Division,Exp.,Ht.,Name,Pos.,Team,Team Logo,Team Roster,Wt.,Ht,feet,inch
0,NaN,NaN,"Atlanta, GA",Minnesota,NFC,NFC-South,NaN,nan,"Lynn, Jack",LB,Falcons,https://cpt.azureedge.net/NFLTeamImages/falcon...,http://www.atlantafalcons.com/team/player-rost...,0,NaN,0.0,0.0
1,NaN,NaN,"East Rutherford, NJ",Akron,NFC,NFC-East,R,6-3,"Lane, Jerome",WR,Giants,https://cpt.azureedge.net/NFLTeamImages/giants...,http://www.giants.com/team/roster.html,220,6-3,6.0,3.0
2,NaN,NaN,"East Rutherford, NJ",Iowa State,NFC,NFC-East,R,5-10,"Tribune, Nigel",CB,Giants,https://cpt.azureedge.net/NFLTeamImages/giants...,http://www.giants.com/team/roster.html,179,5-10,5.0,10.0
3,1,NaN,"Atlanta, GA",Georgia,NFC,NFC-South,R,6-0,"Davis, Reggie",WR,Falcons,https://cpt.azureedge.net/NFLTeamImages/falcon...,http://www.atlantafalcons.com/team/player-rost...,170,6-0,6.0,0.0
4,11,NaN,"Denver, CO",Louisiana Tech,AFC,AFC-West,R,5-11,"Henderson, Carlos",WR,Broncos,https://cpt.azureedge.net/NFLTeamImages/bronco...,http://www.denverbroncos.com/team/roster.html,199,5-11,5.0,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2863,92,39.0,"Pittsburg, PA",Kent State,AFC,AFC-North,15,6-0,"Harrison, James",LB,Steelers,https://cpt.azureedge.net/NFLTeamImages/steele...,http://www.steelers.com/team/roster.html,242,6-0,6.0,0.0
2864,9,40.0,"Houston, TX",Texas A&M,AFC,AFC-South,17,6-2,"Lechler, Shane",P,Texans,https://cpt.azureedge.net/NFLTeamImages/texans...,http://www.houstontexans.com/team/roster.html,230,6-2,6.0,2.0
2865,3,42.0,"Atlanta, GA",Baylor,NFC,NFC-South,16,5-9,"Bryant, Matt",K,Falcons,https://cpt.azureedge.net/NFLTeamImages/falcon...,http://www.atlantafalcons.com/team/player-rost...,203,5-9,5.0,9.0
2866,4,42.0,"Glendale, AZ",Texas,NFC,NFC-West,18,5-11,"Dawson, Phil",K,Cardinals,https://cpt.azureedge.net/NFLTeamImages/cardin...,http://www.azcardinals.com/roster/player-roste...,200,5-11,5.0,11.0
2867,4,44.0,"Indianapolis, IN",South Dakota State,AFC,AFC-South,22,6-0,"Vinatieri, Adam",K,Colts,https://cpt.azureedge.net/NFLTeamImages/colts.png,http://www.colts.com/team/roster.html,206,6-0,6.0,0.0

In [89]:
# convert feet to inches
df.loc[df['feet']<10, 'feet'] *= 12
df

,#,Age,City,College,Conference,Division,Exp.,Ht.,Name,Pos.,Team,Team Logo,Team Roster,Wt.,Ht,feet,inch
0,NaN,NaN,"Atlanta, GA",Minnesota,NFC,NFC-South,NaN,nan,"Lynn, Jack",LB,Falcons,https://cpt.azureedge.net/NFLTeamImages/falcon...,http://www.atlantafalcons.com/team/player-rost...,0,NaN,0.0,0.0
1,NaN,NaN,"East Rutherford, NJ",Akron,NFC,NFC-East,R,6-3,"Lane, Jerome",WR,Giants,https://cpt.azureedge.net/NFLTeamImages/giants...,http://www.giants.com/team/roster.html,220,6-3,72.0,3.0
2,NaN,NaN,"East Rutherford, NJ",Iowa State,NFC,NFC-East,R,5-10,"Tribune, Nigel",CB,Giants,https://cpt.azureedge.net/NFLTeamImages/giants...,http://www.giants.com/team/roster.html,179,5-10,60.0,10.0
3,1,NaN,"Atlanta, GA",Georgia,NFC,NFC-South,R,6-0,"Davis, Reggie",WR,Falcons,https://cpt.azureedge.net/NFLTeamImages/falcon...,http://www.atlantafalcons.com/team/player-rost...,170,6-0,72.0,0.0
4,11,NaN,"Denver, CO",Louisiana Tech,AFC,AFC-West,R,5-11,"Henderson, Carlos",WR,Broncos,https://cpt.azureedge.net/NFLTeamImages/bronco...,http://www.denverbroncos.com/team/roster.html,199,5-11,60.0,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2863,92,39.0,"Pittsburg, PA",Kent State,AFC,AFC-North,15,6-0,"Harrison, James",LB,Steelers,https://cpt.azureedge.net/NFLTeamImages/steele...,http://www.steelers.com/team/roster.html,242,6-0,72.0,0.0
2864,9,40.0,"Houston, TX",Texas A&M,AFC,AFC-South,17,6-2,"Lechler, Shane",P,Texans,https://cpt.azureedge.net/NFLTeamImages/texans...,http://www.houstontexans.com/team/roster.html,230,6-2,72.0,2.0
2865,3,42.0,"Atlanta, GA",Baylor,NFC,NFC-South,16,5-9,"Bryant, Matt",K,Falcons,https://cpt.azureedge.net/NFLTeamImages/falcon...,http://www.atlantafalcons.com/team/player-rost...,203,5-9,60.0,9.0
2866,4,42.0,"Glendale, AZ",Texas,NFC,NFC-West,18,5-11,"Dawson, Phil",K,Cardinals,https://cpt.azureedge.net/NFLTeamImages/cardin...,http://www.azcardinals.com/roster/player-roste...,200,5-11,60.0,11.0
2867,4,44.0,"Indianapolis, IN",South Dakota State,AFC,AFC-South,22,6-0,"Vinatieri, Adam",K,Colts,https://cpt.azureedge.net/NFLTeamImages/colts.png,http://www.colts.com/team/roster.html,206,6-0,72.0,0.0

In [91]:
# add inch to table
df['h_in_inch'] = df.feet + df.inch
df

,#,Age,City,College,Conference,Division,Exp.,Ht.,Name,Pos.,Team,Team Logo,Team Roster,Wt.,Ht,feet,inch,h_in_inch
0,NaN,NaN,"Atlanta, GA",Minnesota,NFC,NFC-South,NaN,nan,"Lynn, Jack",LB,Falcons,https://cpt.azureedge.net/NFLTeamImages/falcon...,http://www.atlantafalcons.com/team/player-rost...,0,NaN,0.0,0.0,0.0
1,NaN,NaN,"East Rutherford, NJ",Akron,NFC,NFC-East,R,6-3,"Lane, Jerome",WR,Giants,https://cpt.azureedge.net/NFLTeamImages/giants...,http://www.giants.com/team/roster.html,220,6-3,72.0,3.0,75.0
2,NaN,NaN,"East Rutherford, NJ",Iowa State,NFC,NFC-East,R,5-10,"Tribune, Nigel",CB,Giants,https://cpt.azureedge.net/NFLTeamImages/giants...,http://www.giants.com/team/roster.html,179,5-10,60.0,10.0,70.0
3,1,NaN,"Atlanta, GA",Georgia,NFC,NFC-South,R,6-0,"Davis, Reggie",WR,Falcons,https://cpt.azureedge.net/NFLTeamImages/falcon...,http://www.atlantafalcons.com/team/player-rost...,170,6-0,72.0,0.0,72.0
4,11,NaN,"Denver, CO",Louisiana Tech,AFC,AFC-West,R,5-11,"Henderson, Carlos",WR,Broncos,https://cpt.azureedge.net/NFLTeamImages/bronco...,http://www.denverbroncos.com/team/roster.html,199,5-11,60.0,11.0,71.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2863,92,39.0,"Pittsburg, PA",Kent State,AFC,AFC-North,15,6-0,"Harrison, James",LB,Steelers,https://cpt.azureedge.net/NFLTeamImages/steele...,http://www.steelers.com/team/roster.html,242,6-0,72.0,0.0,72.0
2864,9,40.0,"Houston, TX",Texas A&M,AFC,AFC-South,17,6-2,"Lechler, Shane",P,Texans,https://cpt.azureedge.net/NFLTeamImages/texans...,http://www.houstontexans.com/team/roster.html,230,6-2,72.0,2.0,74.0
2865,3,42.0,"Atlanta, GA",Baylor,NFC,NFC-South,16,5-9,"Bryant, Matt",K,Falcons,https://cpt.azureedge.net/NFLTeamImages/falcon...,http://www.atlantafalcons.com/team/player-rost...,203,5-9,60.0,9.0,69.0
2866,4,42.0,"Glendale, AZ",Texas,NFC,NFC-West,18,5-11,"Dawson, Phil",K,Cardinals,https://cpt.azureedge.net/NFLTeamImages/cardin...,http://www.azcardinals.com/roster/player-roste...,200,5-11,60.0,11.0,71.0
2867,4,44.0,"Indianapolis, IN",South Dakota State,AFC,AFC-South,22,6-0,"Vinatieri, Adam",K,Colts,https://cpt.azureedge.net/NFLTeamImages/colts.png,http://www.colts.com/team/roster.html,206,6-0,72.0,0.0,72.0

In [92]:
df['Wt.'].replace('6-3', 0)

0         0
1       220
2       179
3       170
4       199
       ...
2863    242
2864    230
2865    203
2866    200
2867    206
Name: Wt., Length: 2868, dtype: int64

In [93]:
df

,#,Age,City,College,Conference,Division,Exp.,Ht.,Name,Pos.,Team,Team Logo,Team Roster,Wt.,Ht,feet,inch,h_in_inch
0,NaN,NaN,"Atlanta, GA",Minnesota,NFC,NFC-South,NaN,nan,"Lynn, Jack",LB,Falcons,https://cpt.azureedge.net/NFLTeamImages/falcon...,http://www.atlantafalcons.com/team/player-rost...,0,NaN,0.0,0.0,0.0
1,NaN,NaN,"East Rutherford, NJ",Akron,NFC,NFC-East,R,6-3,"Lane, Jerome",WR,Giants,https://cpt.azureedge.net/NFLTeamImages/giants...,http://www.giants.com/team/roster.html,220,6-3,72.0,3.0,75.0
2,NaN,NaN,"East Rutherford, NJ",Iowa State,NFC,NFC-East,R,5-10,"Tribune, Nigel",CB,Giants,https://cpt.azureedge.net/NFLTeamImages/giants...,http://www.giants.com/team/roster.html,179,5-10,60.0,10.0,70.0
3,1,NaN,"Atlanta, GA",Georgia,NFC,NFC-South,R,6-0,"Davis, Reggie",WR,Falcons,https://cpt.azureedge.net/NFLTeamImages/falcon...,http://www.atlantafalcons.com/team/player-rost...,170,6-0,72.0,0.0,72.0
4,11,NaN,"Denver, CO",Louisiana Tech,AFC,AFC-West,R,5-11,"Henderson, Carlos",WR,Broncos,https://cpt.azureedge.net/NFLTeamImages/bronco...,http://www.denverbroncos.com/team/roster.html,199,5-11,60.0,11.0,71.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2863,92,39.0,"Pittsburg, PA",Kent State,AFC,AFC-North,15,6-0,"Harrison, James",LB,Steelers,https://cpt.azureedge.net/NFLTeamImages/steele...,http://www.steelers.com/team/roster.html,242,6-0,72.0,0.0,72.0
2864,9,40.0,"Houston, TX",Texas A&M,AFC,AFC-South,17,6-2,"Lechler, Shane",P,Texans,https://cpt.azureedge.net/NFLTeamImages/texans...,http://www.houstontexans.com/team/roster.html,230,6-2,72.0,2.0,74.0
2865,3,42.0,"Atlanta, GA",Baylor,NFC,NFC-South,16,5-9,"Bryant, Matt",K,Falcons,https://cpt.azureedge.net/NFLTeamImages/falcon...,http://www.atlantafalcons.com/team/player-rost...,203,5-9,60.0,9.0,69.0
2866,4,42.0,"Glendale, AZ",Texas,NFC,NFC-West,18,5-11,"Dawson, Phil",K,Cardinals,https://cpt.azureedge.net/NFLTeamImages/cardin...,http://www.azcardinals.com/roster/player-roste...,200,5-11,60.0,11.0,71.0
2867,4,44.0,"Indianapolis, IN",South Dakota State,AFC,AFC-South,22,6-0,"Vinatieri, Adam",K,Colts,https://cpt.azureedge.net/NFLTeamImages/colts.png,http://www.colts.com/team/roster.html,206,6-0,72.0,0.0,72.0

In [98]:
# below code did not work well, keep as info
# df['Ht_t'] = df['Ht.'].str.replace('-', '.').astype(float)
# df.loc[df['Ht.']>10, 'Ht.'] /= 12

In [99]:
# Height to numeric, and clean up
def height_to_numerical(height):
    """
    Convert string to total inches
    Ex. '5-11' --> 71
    """
    feet = height.split('-')[0]
    inches = height.split('-')[1]
    return int(feet)*12 + int(inches)

def clean_height(val):
    try:
        # height is always in inches
        height = int(val)
    except:
        height = height_to_numerical(val)

    return height

In [100]:
df

,#,Age,City,College,Conference,Division,Exp.,Ht.,Name,Pos.,Team,Team Logo,Team Roster,Wt.,Ht,feet,inch,h_in_inch
0,NaN,NaN,"Atlanta, GA",Minnesota,NFC,NFC-South,NaN,nan,"Lynn, Jack",LB,Falcons,https://cpt.azureedge.net/NFLTeamImages/falcon...,http://www.atlantafalcons.com/team/player-rost...,0,NaN,0.0,0.0,0.0
1,NaN,NaN,"East Rutherford, NJ",Akron,NFC,NFC-East,R,6-3,"Lane, Jerome",WR,Giants,https://cpt.azureedge.net/NFLTeamImages/giants...,http://www.giants.com/team/roster.html,220,6-3,72.0,3.0,75.0
2,NaN,NaN,"East Rutherford, NJ",Iowa State,NFC,NFC-East,R,5-10,"Tribune, Nigel",CB,Giants,https://cpt.azureedge.net/NFLTeamImages/giants...,http://www.giants.com/team/roster.html,179,5-10,60.0,10.0,70.0
3,1,NaN,"Atlanta, GA",Georgia,NFC,NFC-South,R,6-0,"Davis, Reggie",WR,Falcons,https://cpt.azureedge.net/NFLTeamImages/falcon...,http://www.atlantafalcons.com/team/player-rost...,170,6-0,72.0,0.0,72.0
4,11,NaN,"Denver, CO",Louisiana Tech,AFC,AFC-West,R,5-11,"Henderson, Carlos",WR,Broncos,https://cpt.azureedge.net/NFLTeamImages/bronco...,http://www.denverbroncos.com/team/roster.html,199,5-11,60.0,11.0,71.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2863,92,39.0,"Pittsburg, PA",Kent State,AFC,AFC-North,15,6-0,"Harrison, James",LB,Steelers,https://cpt.azureedge.net/NFLTeamImages/steele...,http://www.steelers.com/team/roster.html,242,6-0,72.0,0.0,72.0
2864,9,40.0,"Houston, TX",Texas A&M,AFC,AFC-South,17,6-2,"Lechler, Shane",P,Texans,https://cpt.azureedge.net/NFLTeamImages/texans...,http://www.houstontexans.com/team/roster.html,230,6-2,72.0,2.0,74.0
2865,3,42.0,"Atlanta, GA",Baylor,NFC,NFC-South,16,5-9,"Bryant, Matt",K,Falcons,https://cpt.azureedge.net/NFLTeamImages/falcon...,http://www.atlantafalcons.com/team/player-rost...,203,5-9,60.0,9.0,69.0
2866,4,42.0,"Glendale, AZ",Texas,NFC,NFC-West,18,5-11,"Dawson, Phil",K,Cardinals,https://cpt.azureedge.net/NFLTeamImages/cardin...,http://www.azcardinals.com/roster/player-roste...,200,5-11,60.0,11.0,71.0
2867,4,44.0,"Indianapolis, IN",South Dakota State,AFC,AFC-South,22,6-0,"Vinatieri, Adam",K,Colts,https://cpt.azureedge.net/NFLTeamImages/colts.png,http://www.colts.com/team/roster.html,206,6-0,72.0,0.0,72.0

In [101]:
df.loc[df.College == 'Akron']

,#,Age,City,College,Conference,Division,Exp.,Ht.,Name,Pos.,Team,Team Logo,Team Roster,Wt.,Ht,feet,inch,h_in_inch
1,NaN,NaN,"East Rutherford, NJ",Akron,NFC,NFC-East,R,6-3,"Lane, Jerome",WR,Giants,https://cpt.azureedge.net/NFLTeamImages/giants...,http://www.giants.com/team/roster.html,220,6-3,72.0,3.0,75.0
248,37,22.0,"Houston, TX",Akron,AFC,AFC-South,R,6-0,"Jones, Bryce",CB,Texans,https://cpt.azureedge.net/NFLTeamImages/texans...,http://www.houstontexans.com/team/roster.html,180,6-0,72.0,0.0,72.0
377,68,22.0,"Cleveland, OH",Akron,AFC,AFC-North,R,6-1,"Marcus, Jamal",DL,Browns,https://cpt.azureedge.net/NFLTeamImages/browns...,http://www.clevelandbrowns.com/team/roster.html,240,6-1,72.0,1.0,73.0
620,33,23.0,"Miami, FL",Akron,AFC,AFC-East,R,6-0,"Hope, Larry",CB,Dolphins,https://cpt.azureedge.net/NFLTeamImages/dolphi...,http://www.miamidolphins.com/team/player-roste...,192,6-0,72.0,0.0,72.0
757,57,23.0,"San Diego, CA",Akron,AFC,AFC-West,2,5-11,"Brown, Jatavis",OLB,Chargers,https://cpt.azureedge.net/NFLTeamImages/charge...,http://www.chargers.com/team/roster,221,5-11,60.0,11.0,71.0
768,59,23.0,"Kansas City, MO",Akron,AFC,AFC-West,3,6-0,"March-Lillard, Justin",LB,Chiefs,https://cpt.azureedge.net/NFLTeamImages/chiefs...,http://www.chiefs.com/team/roster.html,222,6-0,72.0,0.0,72.0
771,6,23.0,"Indianapolis, IN",Akron,AFC,AFC-South,R,5-7,"Natson, JoJo",WR,Colts,https://cpt.azureedge.net/NFLTeamImages/colts.png,http://www.colts.com/team/roster.html,159,5-7,60.0,7.0,67.0
1170,42,24.0,"Glendale, AZ",Akron,NFC,NFC-West,1,6-3,"Capi, Cap",OLB,Cardinals,https://cpt.azureedge.net/NFLTeamImages/cardin...,http://www.azcardinals.com/roster/player-roste...,249,6-3,72.0,3.0,75.0
1285,63W,24.0,"Washington, DC",Akron,NFC,NFC-East,1,6-3,"Williams, Isaiah",T,Redskins,https://cpt.azureedge.net/NFLTeamImages/redski...,http://www.redskins.com/team/roster.html,306,6-3,72.0,3.0,75.0
1999,63,26.0,"Baltimore, MD",Akron,AFC,AFC-North,1,6-4,"Pughsley, Jarrod",G,Ravens,https://cpt.azureedge.net/NFLTeamImages/ravens...,http://www.baltimoreravens.com/team/roster.html,310,6-4,72.0,4.0,76.0

In [118]:
df = df.dropna(axis=1, how='all')
# df[df.College.str.contains('Arkon')]
df

,#,Age,City,College,Conference,Division,Exp.,Ht.,Name,Pos.,Team,Team Logo,Team Roster,Wt.,Ht,feet,inch,h_in_inch
0,NaN,NaN,"Atlanta, GA",Minnesota,NFC,NFC-South,NaN,nan,"Lynn, Jack",LB,Falcons,https://cpt.azureedge.net/NFLTeamImages/falcon...,http://www.atlantafalcons.com/team/player-rost...,0,NaN,0.0,0.0,0.0
1,NaN,NaN,"East Rutherford, NJ",Akron,NFC,NFC-East,R,6-3,"Lane, Jerome",WR,Giants,https://cpt.azureedge.net/NFLTeamImages/giants...,http://www.giants.com/team/roster.html,220,6-3,72.0,3.0,75.0
2,NaN,NaN,"East Rutherford, NJ",Iowa State,NFC,NFC-East,R,5-10,"Tribune, Nigel",CB,Giants,https://cpt.azureedge.net/NFLTeamImages/giants...,http://www.giants.com/team/roster.html,179,5-10,60.0,10.0,70.0
3,1,NaN,"Atlanta, GA",Georgia,NFC,NFC-South,R,6-0,"Davis, Reggie",WR,Falcons,https://cpt.azureedge.net/NFLTeamImages/falcon...,http://www.atlantafalcons.com/team/player-rost...,170,6-0,72.0,0.0,72.0
4,11,NaN,"Denver, CO",Louisiana Tech,AFC,AFC-West,R,5-11,"Henderson, Carlos",WR,Broncos,https://cpt.azureedge.net/NFLTeamImages/bronco...,http://www.denverbroncos.com/team/roster.html,199,5-11,60.0,11.0,71.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2863,92,39.0,"Pittsburg, PA",Kent State,AFC,AFC-North,15,6-0,"Harrison, James",LB,Steelers,https://cpt.azureedge.net/NFLTeamImages/steele...,http://www.steelers.com/team/roster.html,242,6-0,72.0,0.0,72.0
2864,9,40.0,"Houston, TX",Texas A&M,AFC,AFC-South,17,6-2,"Lechler, Shane",P,Texans,https://cpt.azureedge.net/NFLTeamImages/texans...,http://www.houstontexans.com/team/roster.html,230,6-2,72.0,2.0,74.0
2865,3,42.0,"Atlanta, GA",Baylor,NFC,NFC-South,16,5-9,"Bryant, Matt",K,Falcons,https://cpt.azureedge.net/NFLTeamImages/falcon...,http://www.atlantafalcons.com/team/player-rost...,203,5-9,60.0,9.0,69.0
2866,4,42.0,"Glendale, AZ",Texas,NFC,NFC-West,18,5-11,"Dawson, Phil",K,Cardinals,https://cpt.azureedge.net/NFLTeamImages/cardin...,http://www.azcardinals.com/roster/player-roste...,200,5-11,60.0,11.0,71.0
2867,4,44.0,"Indianapolis, IN",South Dakota State,AFC,AFC-South,22,6-0,"Vinatieri, Adam",K,Colts,https://cpt.azureedge.net/NFLTeamImages/colts.png,http://www.colts.com/team/roster.html,206,6-0,72.0,0.0,72.0

In [122]:
df = df.dropna()  # clean up data
df[df.College.str.contains('^S')]   # to avoid cannot convert Nan value error

,#,Age,City,College,Conference,Division,Exp.,Ht.,Name,Pos.,Team,Team Logo,Team Roster,Wt.,Ht,feet,inch,h_in_inch
69,22,21.0,"Charlotte, NC",Stanford,NFC,NFC-South,R,5-11,"McCaffrey, Christian",RB,Panthers,https://cpt.azureedge.net/NFLTeamImages/panthe...,http://www.panthers.com/team/roster.html,205,5-11,60.0,11.0,71.0
73,25,21.0,"Indianapolis, IN",South Florida,AFC,AFC-South,0,6-0,"Mack, Marlon",RB,Colts,https://cpt.azureedge.net/NFLTeamImages/colts.png,http://www.colts.com/team/roster.html,210,6-0,72.0,0.0,72.0
74,25,21.0,"Nashville, TN",Southern California,AFC,AFC-South,R,5-11,"Jackson, Adoree'",CB,Titans,https://cpt.azureedge.net/NFLTeamImages/titans...,http://www.titansonline.com/team/roster.html,185,5-11,60.0,11.0,71.0
100,36,21.0,"Houston, TX",San Diego State,AFC,AFC-South,R,6-0,"Smith, Malik",S,Texans,https://cpt.azureedge.net/NFLTeamImages/texans...,http://www.houstontexans.com/team/roster.html,190,6-0,72.0,0.0,72.0
110,42,21.0,"St. Louis, MO",Southern California,NFC,NFC-West,R,6-1,"Davis, Justin",RB,Rams,https://cpt.azureedge.net/NFLTeamImages/rams.png,http://www.therams.com/team/roster.html,198,6-1,72.0,1.0,73.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2797,24,33.0,"Houston, TX",South Carolina,AFC,AFC-South,11,5-11,"Joseph, Johnathan",CB,Texans,https://cpt.azureedge.net/NFLTeamImages/texans...,http://www.houstontexans.com/team/roster.html,185,5-11,60.0,11.0,71.0
2798,24,33.0,"Tampa, FL",Shippensburg,NFC,NFC-South,11,5-10,"Grimes, Brent",CB,Buccaneers,https://cpt.azureedge.net/NFLTeamImages/bucs.png,http://www.buccaneers.com/team-and-stats/roste...,185,5-10,60.0,10.0,70.0
2822,29,34.0,"New Orleans, LA",Shippensburg,NFC,NFC-South,10,6-0,"Kuhn, John",FB,Saints,https://cpt.azureedge.net/NFLTeamImages/saints...,http://www.neworleanssaints.com/team/roster.html,250,6-0,72.0,0.0,72.0
2855,15,37.0,"East Rutherford, NJ",Sam Houston State,AFC,AFC-East,15,6-4,"McCown, Josh",QB,Jets,https://cpt.azureedge.net/NFLTeamImages/jets.png,http://www.newyorkjets.com/team/roster.html,218,6-4,72.0,4.0,76.0
2867,4,44.0,"Indianapolis, IN",South Dakota State,AFC,AFC-South,22,6-0,"Vinatieri, Adam",K,Colts,https://cpt.azureedge.net/NFLTeamImages/colts.png,http://www.colts.com/team/roster.html,206,6-0,72.0,0.0,72.0

In [125]:
# find values starting with S
df.College.str.findall('^S.+').sum()[:5]

['Stanford',
 'South Florida',
 'Southern California',
 'San Diego State',
 'Southern California']

In [128]:
# find values starting with S
# \S without space
df.College.str.findall('^S.\\S+').sum()[:5]

['Stanford', 'South', 'Southern', 'San', 'Southern']

In [129]:
# find length of words
df.College.str.len()

48       8
49       8
50       3
51       8
52       7
        ..
2863    10
2864     9
2865     6
2866     5
2867    18
Name: College, Length: 2809, dtype: int64

In [130]:
# uppercase
df.College.str.upper()

48                COLORADO
49                OHIO ST.
50                     USC
51                OKLAHOMA
52                 ALABAMA
               ...
2863            KENT STATE
2864             TEXAS A&M
2865                BAYLOR
2866                 TEXAS
2867    SOUTH DAKOTA STATE
Name: College, Length: 2809, dtype: object

### String Manipulation

In [134]:
ebola = pd.read_csv('country_timeseries.csv', parse_dates = True)
df

            Date  Day country_with_cases   count
0       1/5/2015  289       Cases_Guinea  2776.0
1       1/4/2015  288       Cases_Guinea  2775.0
2       1/3/2015  287       Cases_Guinea  2769.0
3       1/2/2015  286       Cases_Guinea     NaN
4     12/31/2014  284       Cases_Guinea  2730.0
...          ...  ...                ...     ...
1947   3/27/2014    5        Deaths_Mali     NaN
1948   3/26/2014    4        Deaths_Mali     NaN
1949   3/25/2014    3        Deaths_Mali     NaN
1950   3/24/2014    2        Deaths_Mali     NaN
1951   3/22/2014    0        Deaths_Mali     NaN

[1952 rows x 4 columns]

In [135]:
df = ebola.melt(id_vars=['Date','Day'],
                var_name = 'country_with_cases',
                value_name = 'count'                
               )
df

            Date  Day country_with_cases   count
0       1/5/2015  289       Cases_Guinea  2776.0
1       1/4/2015  288       Cases_Guinea  2775.0
2       1/3/2015  287       Cases_Guinea  2769.0
3       1/2/2015  286       Cases_Guinea     NaN
4     12/31/2014  284       Cases_Guinea  2730.0
...          ...  ...                ...     ...
1947   3/27/2014    5        Deaths_Mali     NaN
1948   3/26/2014    4        Deaths_Mali     NaN
1949   3/25/2014    3        Deaths_Mali     NaN
1950   3/24/2014    2        Deaths_Mali     NaN
1951   3/22/2014    0        Deaths_Mali     NaN

[1952 rows x 4 columns]

In [136]:
df['country_with_cases'].unique()

array(['Cases_Guinea', 'Cases_Liberia', 'Cases_SierraLeone',
       'Cases_Nigeria', 'Cases_Senegal', 'Cases_UnitedStates',
       'Cases_Spain', 'Cases_Mali', 'Deaths_Guinea', 'Deaths_Liberia',
       'Deaths_SierraLeone', 'Deaths_Nigeria', 'Deaths_Senegal',
       'Deaths_UnitedStates', 'Deaths_Spain', 'Deaths_Mali'], dtype=object)

In [140]:
# add a new column
df['Dead'] = df['country_with_cases'].str.extract(f'(^D.+)')
df

            Date  Day country_with_cases   count         Dead
0       1/5/2015  289       Cases_Guinea  2776.0          NaN
1       1/4/2015  288       Cases_Guinea  2775.0          NaN
2       1/3/2015  287       Cases_Guinea  2769.0          NaN
3       1/2/2015  286       Cases_Guinea     NaN          NaN
4     12/31/2014  284       Cases_Guinea  2730.0          NaN
...          ...  ...                ...     ...          ...
1947   3/27/2014    5        Deaths_Mali     NaN  Deaths_Mali
1948   3/26/2014    4        Deaths_Mali     NaN  Deaths_Mali
1949   3/25/2014    3        Deaths_Mali     NaN  Deaths_Mali
1950   3/24/2014    2        Deaths_Mali     NaN  Deaths_Mali
1951   3/22/2014    0        Deaths_Mali     NaN  Deaths_Mali

[1952 rows x 5 columns]

In [143]:
df['cases'] = df['country_with_cases'].replace('^D.+', np.nan, regex=True)
df

            Date  Day country_with_cases   count         Dead         cases
0       1/5/2015  289       Cases_Guinea  2776.0          NaN  Cases_Guinea
1       1/4/2015  288       Cases_Guinea  2775.0          NaN  Cases_Guinea
2       1/3/2015  287       Cases_Guinea  2769.0          NaN  Cases_Guinea
3       1/2/2015  286       Cases_Guinea     NaN          NaN  Cases_Guinea
4     12/31/2014  284       Cases_Guinea  2730.0          NaN  Cases_Guinea
...          ...  ...                ...     ...          ...           ...
1947   3/27/2014    5        Deaths_Mali     NaN  Deaths_Mali           NaN
1948   3/26/2014    4        Deaths_Mali     NaN  Deaths_Mali           NaN
1949   3/25/2014    3        Deaths_Mali     NaN  Deaths_Mali           NaN
1950   3/24/2014    2        Deaths_Mali     NaN  Deaths_Mali           NaN
1951   3/22/2014    0        Deaths_Mali     NaN  Deaths_Mali           NaN

[1952 rows x 6 columns]